# Generated by Django 6.1.1 on 2026-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_mission_completed_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme'), ('brutal', 'Brutal')], max_length=64),
        ),
    ]
